<!-- Report Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('report_type', 'Report Type:') !!}
    {!! Form::text('report_type', null, ['class' => 'form-control', 'maxlength' => 100, 'maxlength' => 100]) !!}
</div>

<!-- Generated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('generated_by', 'Generated By:') !!}
    {!! Form::text('generated_by', null, ['class' => 'form-control', 'maxlength' => 100, 'maxlength' => 100]) !!}
</div>

<!-- Report Data Field -->
<div class="form-group col-sm-6">
    {!! Form::label('report_data', 'Report Data:') !!}
    {!! Form::text('report_data', null, ['class' => 'form-control', 'maxlength' => 100, 'maxlength' => 100]) !!}
</div>