<!-- Report Type Field -->
<div class="col-sm-12">
    {!! Form::label('report_type', 'Report Type:') !!}
    <p>{{ $report->report_type }}</p>
</div>

<!-- Generated By Field -->
<div class="col-sm-12">
    {!! Form::label('generated_by', 'Generated By:') !!}
    <p>{{ $report->generated_by }}</p>
</div>

<!-- Report Data Field -->
<div class="col-sm-12">
    {!! Form::label('report_data', 'Report Data:') !!}
    <p>{{ $report->report_data }}</p>
</div>

